# Generated by Django 4.1.5 on 2023-01-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('key_skills', models.TextField(blank=True, verbose_name='Ключевые навыки')),
                ('salary_from', models.CharField(blank=True, max_length=100, verbose_name='Минимальная зарплата')),
                ('salary_to', models.CharField(blank=True, max_length=100, verbose_name='Максимальная зарплата')),
                ('salary_currency', models.CharField(blank=True, max_length=20, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=1000, verbose_name='Город')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
