# Generated by Django 4.1.5 on 2023-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('salary', models.CharField(max_length=30, verbose_name='Зарплата')),
                ('number_of_vacancies', models.IntegerField(verbose_name='Количество вакансий')),
                ('profession', models.CharField(max_length=30, verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=4, verbose_name='Город')),
                ('salary', models.CharField(max_length=30, verbose_name='Зарплата')),
                ('share_of_vacancies', models.IntegerField(verbose_name='Доля вакансии')),
                ('profession', models.CharField(max_length=30, verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='Latest_vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('key_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('salary', models.CharField(max_length=100, verbose_name='Оклад')),
                ('region', models.CharField(max_length=200, verbose_name='Название региона')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('skills', models.CharField(max_length=1000, verbose_name='Навыки')),
            ],
        ),
        migrations.RenameField(
            model_name='job_vacancy',
            old_name='name',
            new_name='title',
        ),
    ]
