# Generated by Django 4.1.5 on 2023-01-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0002_demand_geography_latest_vacancies_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'verbose_name': 'Востребованность', 'verbose_name_plural': 'Востребованность'},
        ),
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name': 'География', 'verbose_name_plural': 'География'},
        ),
        migrations.AlterModelOptions(
            name='latest_vacancies',
            options={'verbose_name': 'Последние вакансии', 'verbose_name_plural': 'Последние вакансии'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
    ]
