# Generated by Django 4.1.5 on 2023-01-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0003_alter_demand_options_alter_geography_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
