# Generated by Django 4.1.5 on 2023-01-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0005_file_alter_job_vacancy_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_vacancies',
            name='salary',
        ),
        migrations.AddField(
            model_name='latest_vacancies',
            name='salary_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='Минимальная зарплата'),
        ),
        migrations.AddField(
            model_name='latest_vacancies',
            name='salary_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Максимальная зарплата'),
        ),
    ]
