# Generated by Django 4.1.5 on 2023-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0006_remove_latest_vacancies_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_vacancies',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=20, verbose_name='Валюта'),
        ),
    ]
