# Generated by Django 4.1.5 on 2023-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0007_latest_vacancies_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_vacancies',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='latest_vacancies',
            name='salary_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Минимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='latest_vacancies',
            name='salary_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Максимальная зарплата'),
        ),
    ]
