# Generated by Django 4.1.5 on 2023-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0008_alter_latest_vacancies_salary_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand_PHP_year_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('salary', models.CharField(max_length=30, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Динамика уровня зарплат по годам для выбранной профессии',
                'verbose_name_plural': 'Динамика уровня зарплат по годам для выбранной профессии',
            },
        ),
        migrations.CreateModel(
            name='Demand_PHP_year_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('number_of_vacancies', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам для выбранной профессии',
                'verbose_name_plural': 'Динамика количества вакансий по годам для выбранной профессии',
            },
        ),
        migrations.CreateModel(
            name='Demand_year_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('salary', models.CharField(max_length=30, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Динамика уровня зарплат по годам',
                'verbose_name_plural': 'Динамика уровня зарплат по годам',
            },
        ),
        migrations.CreateModel(
            name='Demand_year_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('number_of_vacancies', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам',
                'verbose_name_plural': 'Динамика количества вакансий по годам',
            },
        ),
        migrations.CreateModel(
            name='Geography_salary_town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=4, verbose_name='Город')),
                ('salary', models.CharField(max_length=30, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
            },
        ),
        migrations.CreateModel(
            name='Geography_vacancy_town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=4, verbose_name='Город')),
                ('share_of_vacancies', models.IntegerField(verbose_name='Доля вакансии')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
            },
        ),
        migrations.DeleteModel(
            name='Demand',
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
    ]
