# Generated by Django 4.1.5 on 2023-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0009_demand_php_year_salary_demand_php_year_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography_vacancy_town',
            name='share_of_vacancies',
            field=models.FloatField(verbose_name='Доля вакансии'),
        ),
    ]
