# Generated by Django 4.1.5 on 2023-01-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0010_alter_geography_vacancy_town_share_of_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography_salary_town',
            name='salary',
            field=models.FloatField(max_length=30, verbose_name='Зарплата'),
        ),
    ]
