# Generated by Django 4.1.5 on 2023-01-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0012_skills_frequency_alter_geography_salary_town_salary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='skills_year',
            name='skills_frequency',
        ),
        migrations.DeleteModel(
            name='Skills_frequency',
        ),
        migrations.DeleteModel(
            name='Skills_year',
        ),
    ]
