# Generated by Django 4.1.5 on 2023-01-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0013_delete_skills_remove_skills_year_skills_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Skills_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('skills_frequency', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='php_programmer.skills_frequency', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Навыки по годам',
                'verbose_name_plural': 'Навыки по годам',
            },
        ),
    ]
