# Generated by Django 4.1.5 on 2023-01-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0014_skills_frequency_skills_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_php_year_salary',
            name='salary',
            field=models.FloatField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='demand_year_salary',
            name='salary',
            field=models.FloatField(verbose_name='Зарплата'),
        ),
    ]
