# Generated by Django 4.1.5 on 2023-01-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0015_alter_demand_php_year_salary_salary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_vacancy',
        ),
    ]
