# Generated by Django 4.1.5 on 2023-01-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0016_delete_job_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='create_at',
        ),
    ]
