# Generated by Django 4.1.5 on 2023-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0017_remove_file_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
