# Generated by Django 4.1.5 on 2023-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_programmer', '0018_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл vacancies_dif_currencies'),
        ),
    ]
